### ISSUE TITLE
Path is resetting when I come back

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#14]
## Steps to reproduce:
1. Choose a path to install flutter.
2. Click next.
3. Come back and check the path.

## Reference:
https://user-images.githubusercontent.com/35523357/102960979-3750da80-4509-11eb-90c1-9c0cdb6fe0ef.mp4

**Comment by YazeedAlKhalaf** [comment]
Thanks for your concern. I remember doing it on purpose but can't really remember why. But yea it is an easy fix.
