### ISSUE TITLE
Cannot find installer for mac

### ISSUE THREAD

**Issue by saurabh1234** [YazeedAlKhalaf/Flutter_Installer#19]
Is the installer only available for Windows? I cannot find the installer for macOS. Thanks

**Comment by yahu1031** [comment]
@saurabh1234 please do check [here](https://github.com/YazeedAlKhalaf/Flutter_Installer/releases/download/v0.0.6/flutter_installer_v0.0.6_macos.zip) and close this issue.

**Comment by YazeedAlKhalaf** [comment]
@saurabh1234 Latest release [v0.0.8](https://github.com/YazeedAlKhalaf/Flutter_Installer/releases/tag/v0.0.8) has all platforms binaries built.
