### ISSUE TITLE
Doesn't open finder on clicking Browse button

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#20]
latest code build doesn't open finder on clicking Browser button. It wasn't throwing any error too. where the older code works fine on [v0.0.6](https://github.com/YazeedAlKhalaf/Flutter_Installer/releases/tag/v0.0.6).

**Comment by YazeedAlKhalaf** [comment]
This is solved with [v0.0.8](https://github.com/YazeedAlKhalaf/Flutter_Installer/releases/tag/v0.0.8) release.
