### ISSUE TITLE
Mac OS - zshrc

### ISSUE THREAD

**Issue by angeloo** [YazeedAlKhalaf/Flutter_Installer#3]
Hi!

For MacOS version, if we use zshrc, it seems flutter is not added to PATH.

Cheers

**Comment by YazeedAlKhalaf** [comment]
Yea, thanks for opening this issue. 🙏😊

I will look into it. 🚀

**Comment by YazeedAlKhalaf** [comment]
@angeloo  Did you provide your Sudo password correctly? Just to make sure, since adding to the .zshrc requires Sudo password.

**Comment by ThinkSimple** [comment]
> @angeloo Did you provide your Sudo password correctly? Just to make sure, since adding to the .zshrc requires Sudo password.

I'm running into the same issue, my password was 100% correct.

**Comment by YazeedAlKhalaf** [comment]
Ah okay then I will have to investigate and I will find a solution ASAP 😎💙🚀

**Comment by angeloo** [comment]
Yes i did :-)
--------------------------
Angelo Maiorano

ᐧ

**Comment by YazeedAlKhalaf** [comment]
Hello @angeloo @ThinkSimple 

Can you try the new release and tell me if your problem is solved or not.

Thanks 🌹

**Comment by ThinkSimple** [comment]
> Hello @angeloo @ThinkSimple
> 
> Can you try the new release and tell me if your problem is solved or not.
> 
> Thanks 🌹

I downloaded the 0.0.4 version but it still does not work. I can see that it download the flutter sdk to to the documents folder and also unzips it. But flutter commands still do not get recognized. Im using the zsh terminal on a Mac Book Pro running Catalina 10.15.5.

**Comment by YazeedAlKhalaf** [comment]
Hello @angeloo  @ThinkSimple 

I believe that your issue is solved now with v0.0.5. I have changed the way I ask for Sudo password. I ti snow using `osascript`. It is far more secure and better. The path should now be changed.

On my mac, it works correctly now.

Can you check your `.zshrc` after finishing the process of using the installer to see if a new line is added or not?

Thanks 🚀

**Comment by angeloo** [comment]
Hello @YazeedAlKhalaf,

Maybe I'm wrong, but I d'ont see a new release, and I haven't setup my env to compile a flutter desktop.

Can you explain me how I can test that?

Thanks! 👍

**Comment by YazeedAlKhalaf** [comment]
I am releasing it today. I am currently doing last tests to make sure everything is okay. Don't worry you're not wrong It is just I sent the message early. Check in about an hour and you'll find the release up and running.

**Comment by YazeedAlKhalaf** [comment]
@angeloo It is now published, windows executable not there since I can't build it rn. But you need the macOS one so I guess you're good to go.

**Comment by ThinkSimple** [comment]
> @angeloo It is now published, windows executable not there since I can't build it rn. But you need the macOS one so I guess you're good to go.

Its working now!

**Comment by YazeedAlKhalaf** [comment]
Great! I will wait for @angeloo to respond before closing the issue! 🚀

**Comment by YazeedAlKhalaf** [comment]
@angeloo  Can you confirm if it works?

**Comment by angeloo** [comment]
@YazeedAlKhalaf Sorry, i was on day off without computer.

Yeah it works! great! 🚀

**Comment by YazeedAlKhalaf** [comment]
Okay I feel safe to lose this issue 🚀🌹
