### ISSUE TITLE
Better use git [clone] commands instead "curl" in 'Procees.run()'

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#6]
Hello there again 😆,

I would like to suggest you to use git clone command in **Process.run()**. As I have seen the command in installation console you are using
```cmd
curl -o flutter_windows_1.17.5-stable.zip https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.5-stable.zip
```
Here, it gonna take long time to download it and to extract it. so instead using clone will save the time ⏳️ and also space.

I'm working on it. and it is about to complete please do check once I request a pull.

Regards 💙

**Comment by csells** [comment]
We need to download the tarballs on all platforms so as to not mess with the analytics.

**Comment by yahu1031** [comment]
@csells 
I agree that. But if you don't mind, could you please do check my #4 #5 issues too. then you will understand why I suggest this.

Regards.

**Comment by csells** [comment]
There's no reason to use curl or to start a new process; Dart has a full network and file system stack. I brought this up as feedback initially but it was not addressed.

**Comment by yahu1031** [comment]
@csells As the code uses API services in multiple files, It becomes complex to me too search  the whole code. I really appreciate your hard work towards it. But we can build/code this much simpler(suggestion).

**Comment by csells** [comment]
Again. No. We can't.
