### ISSUE TITLE
Publishable packages can't have git dependencies. in pubspec.yaml

### ISSUE THREAD

**Issue by yahu1031** [YazeedAlKhalaf/Flutter_Installer#8]
```
Publishable packages can't have git dependencies. 
Try adding a 'publish_to: none' entry to mark the package as not for publishing or remove the git dependency.
```
It gives warning if we use git for the packages which are in [pub.dev](https://pub.dev).

**Reference Image**

<img src="https://cdn.discordapp.com/attachments/756903745241088011/772595941991383050/2020-11-02_03-53.png"/>

**OS**: Linux-distro ([ParrotOS](https://www.parrotsec.org/))

**Flutter Channel**: Master

```console
┌─[minnu@parrot]─[~]
└──╼ $flutter --version
Flutter 1.24.0-7.0.pre.44 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5511abd90f (12 hours ago) • 2020-11-01 16:13:03 +0530
Engine • revision 3460519398
Tools • Dart 2.12.0 (build 2.12.0-3.0.dev)
```

## Fix ##

Adding 
```yaml
publish_to: 'none'
```
will fix this.
As we are not publishing this Installer in [pub.dev](https://pub.dev), we can add `publish_to: 'none'`.

**Comment by YazeedAlKhalaf** [comment]
Thanks a lot @yahu1031 
You have been contributing a lot to this project 🚀

**Comment by YazeedAlKhalaf** [comment]
Can you check if this issue still exists as I can't reproduce it?

**Comment by yahu1031** [comment]
nope it doesn't I will close it

**Comment by Zeynal7** [comment]
where did you add 
    publish_to: 'none'?

**Comment by EshetuLucas** [comment]
can you please show where exactly to add  "publish_to: none"

**Comment by yahu1031** [comment]
@EshetuLucas in `pubspec.yaml` after the `version:***`

**Comment by LeDuyTho** [comment]
I fixed this error by some step:
1. Add "publish_to: none" in pubspec.yalm of your project, sample:

name: my_appname
description: My_des

publish_to: 'none'

2. Delete cache (if exists) in side folder:
C:\Users\<MY_COMPUTER_USER_NAME>\AppData\Local\Pub\Cache\git\cache

3. In pubspec.yalm, add github package like this:

  my_package:
    git:
      url: https://github.com/<My_github_name>/<my_package>.git
      ref: master

Note: Don't use url: git://
** If all above not work, you can delete pub_cache folder inside your flutter sdk folder.
